### ISSUE TITLE
Does not work on macOS due to line endings

### ISSUE THREAD

**Issue by timbru31** [HansHammel/license-compatibility-checker#1] opened 2017-03-25 16:20 UTC
After installing on macOS I'm unable to run the cli (`$ license-compatibility-checker`) because of the error:

`env: node\r: No such file or directory`

It seems you have uploaded the files CRLF line endings instead of LF.  
Could you possibly switch to LF? (e.g. via `.gitattributes` or `.editorconfig`)

**Comment by edouard-lopez** [comment] 2017-03-27 10:27
same on Linux Mint/Ubuntu

**Comment by majnu-campact** [comment] 2017-07-27 11:24
Same problem here on macOS. Any chance that this will be fixed?

**Comment by HansHammel** [comment] 2018-07-06 13:10
Cannot reproduce the issue. I published a new version and added a bin script test. On travis mac and linux builds are all passing. So, I am closing this for now.

**Closed as completed by HansHammel** 2018-07-06 13:10 UTC
